Add quiet mode and echoerr function

diff --git a/bin/bingdaily b/bin/bingdaily
--- a/bin/bingdaily
+++ b/bin/bingdaily
@@ -1,13 +1,13 @@
 #!/usr/bin/env bash
 #
 # Created:         Mi 2021-02-17 21:23:22 CET
-# Last Modified:   Mo 2021-02-22 01:03:33 CET
+# Last Modified:   Fri 2021-03-05 09:57:14 CET
 #
 # bingdaily:
 #   Downloads the daily Bing wallpaper
 
 # Help text
-usage() {
+usage () {
 cat << EOF
 
 Usage: bingdaily [options]
@@ -20,9 +20,13 @@ OPTIONS:
    -d DAY         Select day (default: 0=current, 1=yesterday, ...)
    -r RESOLUTION  Select image resolution (default: UHD)
    -y             Create output directories and files without asking
+   -q             Quiet mode
    -h             Show this message
 EOF
 }
+
+# Echo error messages on STDERR
+echoerr () { cat <<< "$@" 1>&2; }
 
 # Overwrite exxisting files
 YES=0
@@ -39,20 +43,25 @@ OUTDIR="$(xdg-user-dir PICTURES)/Bing"
 # For day (0=current; 1=yesterday... so on)
 DAY=0
 
+# Quiet mode
+QUIET=0
+
 # Process options
-while getopts p:m:d:r:yh OPTION
+while getopts p:m:d:r:yqh OPTION
 do
     case "${OPTION}"
     in
         p)  OUTDIR=${OPTARG}
-            ;;
-        y)  YES=1
             ;;
         m)  MARKET=${OPTARG}
             ;;
         d)  DAY=${OPTARG}
             ;;
         r)  RESOLUTION=${OPTARG}
+            ;;
+        y)  YES=1
+            ;;
+        q)  QUIET=1
             ;;
         h)  usage
             exit 0
@@ -65,6 +74,9 @@ done
 
 # Skip options
 shift $((OPTIND-1))
+
+# Switch to quiet mode
+[ "${QUIET}" -eq 1 ] && exec 1>/dev/null
 
 # Base URL
 BING="https://www.bing.com/"
@@ -81,7 +93,7 @@ RESP=$(wget --quiet --output-document=- "${BING}/${API}")
 ecode=$?
 if [ "$ecode" -gt 0 ]
 then
-    echo "No connection to ${BING}"
+    echoerr "No connection to ${BING}"
     exit 2
 fi
 
@@ -119,6 +131,13 @@ echo "URL: ${FILEURL}"
 if [ ! -d "${OUTDIR}" ]
 then
 
+    # Check quiet mode
+    if [ "${QUIET}" -eq 1 ]
+    then
+        echoerr "Download folder "${OUTDIR}" does not exist."
+        exit 2
+    fi
+
     # Interactive block
     if [ "$YES" -eq 0 ]
     then
@@ -144,12 +163,19 @@ echo "Folder: ${OUTDIR}"
 if [ -f "${OUTDIR}/${FILENAME}" ]
 then
 
+    # Check quiet mode
+    if [ "${QUIET}" -eq 1 ]
+    then
+        echoerr "Output file "${OUTDIR}/${FILENAME}" already exists"
+        exit 3
+    fi
+
     # Interactive block
     if [ "${YES}" -eq 0 ]
     then
         while true
         do
-            read -r -p "Output file '${OUTDIR}/${FILENAME}' already exists. Replace ot? [Yn] " yn
+            read -r -p "Output file '${OUTDIR}/${FILENAME}' already exists. Replace it? [Yn] " yn
             case $yn in
                 [Yy]*) break ;;
                 [Nn]*) exit 3 ;;
@@ -174,6 +200,6 @@ then
     KBYTES=$(echo "scale=1; $(stat -c %s "${OUTDIR}/${FILENAME}")/1024" | bc -l)
     echo "Status: ok (${KBYTES} kB written)"
 else
-    echo "Status: Failed (wget error: $ecode)" >&2
+    echoerr echo "Status: Failed (wget error: $ecode)"
     exit 4
 fi
